// <auto-generated />
using System;
using DiabloII.Items.Api.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiabloII.Items.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DiabloII.Items.Api.DbContext.Suggestions.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreationDateUtc");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("DiabloII.Items.Api.DbContext.Suggestions.Suggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Content")
                        .IsUnique();

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("DiabloII.Items.Api.DbContext.Suggestions.SuggestionVote", b =>
                {
                    b.Property<Guid>("SuggestionId");

                    b.Property<string>("Ip")
                        .HasMaxLength(15);

                    b.Property<Guid>("Id");

                    b.Property<bool>("IsPositive");

                    b.Property<Guid?>("SuggestionId1");

                    b.HasKey("SuggestionId", "Ip");

                    b.HasAlternateKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("SuggestionId1");

                    b.ToTable("SuggestionVotes");
                });

            modelBuilder.Entity("DiabloII.Items.Api.DbContext.Suggestions.SuggestionVote", b =>
                {
                    b.HasOne("DiabloII.Items.Api.DbContext.Suggestions.Suggestion")
                        .WithMany("Votes")
                        .HasForeignKey("SuggestionId1");
                });
#pragma warning restore 612, 618
        }
    }
}
