export enum ItemActionName
{
    ITEM_SEARCH = "ITEM_SEARCH",
    ITEM_SEARCH_STARTED = "ITEM_SEARCH_STARTED",
    ITEM_SEARCH_COMPLETED = "ITEM_SEARCH_DONE",
    ITEM_SEARCH_FAILED = "ITEM_SEARCH_FAILED"
}